version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      API_PORT: 8000
      DATABASE_URL: postgresql://appuser:apppassword@db:5432/appdb
      SECRET_KEY: supersecretkey
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  db_data: